### PR TITLE
Fixes issue #5 Add favicon to Awareness app

### LINKED ISSUE #5: Add favicon
Add favicon for the app.

### PR DESCRIPTION
**Pull request by anupamasok**
Fixes #5 
Added favicons to the page HEAD. Tested OK.

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
@anupamasok I noticed the package.json has changed. Was it necessary?

**Comment by anupamasok** [comment]
@prometheansacrifice npm audit was showing Prototype Pollution vulnerabilities. Ran npm audit fix to fix those.

**Comment by prometheansacrifice** [comment]
Got it. Thanks!

**Comment by bodhish** [comment]
@prometheansacrifice  can you review and merge this PR

**Pull request merged**
